version: '3'
services:
  postgresql:
#    image: postgres:14.1-alpine
    build:
      dockerfile: Dockerfile
      context: docker/postgresql
    container_name: sb-postgres
    environment:
      - POSTGRES_DB=sheetbit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"