version: '3'
services:
  postgresql:
    build:
      dockerfile: Dockerfile
      context: docker/postgresql
    container_name: sb-postgres
    environment:
      - POSTGRES_DB=sheetbit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  keycloak:
    build:
      dockerfile: Dockerfile
      context: docker/keycloak
    container_name: sb-keycloak
    environment:
      - KEYCLOAK_USER=root
      - KEYCLOAK_PASSWORD=root
      - KEYCLOAK_ADMIN=root
      - KEYCLOAK_ADMIN_PASSWORD=root
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    ports:
      - "9797:8080"