package com.buczi.sheetbit.core

enum class Faction {
    SPACE_MARINES,
    GREY_KNIGHTS,
    ASTRA_MILITARUM,
    ADEPTA_SORORITAS,
    ADEPTUS_CUSTODES,
    ADEPTUS_MECHANICUS,
    IMPERIAL_KNIGHTS,
    CHAOS_SPACE_MARINES,
    ORKS,
    AELDARI,
    DRUKHARI,
    NECRONS,
    TAU_EMPIRE,
    TYRANIDS,
    GENSTEALER_CULTS,
    CHAOS_KNIGHTS,
    LEAGUES_OF_VOTANN,
    NONE
}